set nu           "set number"
set sw=4         "set shiftwidth -indent level- into 4 space" 
set ruler        "display cursor position on the last line of the screen"
set showcmd      "show partial command"
set ts=4         "converted tabstop into four spaces"
set showmatch    "set show matching parenthesis"
set incsearch    "show search matches as you type"
set autoindent   "Auto indent level"
set expandtab    "turn tab to spaces"
